// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.Entities;

namespace eShop.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eShop.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietDonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDonHangId");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("eShop.Entities.ChiTietGioHang", b =>
                {
                    b.Property<int>("ChiTietGioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietGioHangId");

                    b.HasIndex("KhachHangId")
                        .IsUnique();

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietGioHang");
                });

            modelBuilder.Entity("eShop.Entities.DanhGiaDonHang", b =>
                {
                    b.Property<int>("DanhGiaDonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhGiaDonHangId");

                    b.HasIndex("DonHangId")
                        .IsUnique();

                    b.ToTable("DanhGiaDonHang");
                });

            modelBuilder.Entity("eShop.Entities.DanhGiaSanPham", b =>
                {
                    b.Property<int>("DanhGiaSanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChiTietDonHangId")
                        .HasColumnType("int");

                    b.Property<float>("Diem")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhGiaSanPhamId");

                    b.HasIndex("ChiTietDonHangId")
                        .IsUnique();

                    b.ToTable("DanhGiaSanPham");
                });

            modelBuilder.Entity("eShop.Entities.DoanhThuNguoiBan", b =>
                {
                    b.Property<int>("DoanhThuNguoiBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DoanhThu")
                        .HasColumnType("real");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiBanId")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("DoanhThuNguoiBanId");

                    b.HasIndex("NguoiBanId");

                    b.ToTable("DoanhThuNguoiBan");
                });

            modelBuilder.Entity("eShop.Entities.DonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiBanId")
                        .HasColumnType("int");

                    b.Property<float>("PhiShip")
                        .HasColumnType("real");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.HasKey("DonHangId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NguoiBanId");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("eShop.Entities.HoSoDangKyBanHang", b =>
                {
                    b.Property<int>("HoSoDangKyBanHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGiayCNATVSTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGiayPhepKD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCuaHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoSoDangKyBanHangId");

                    b.ToTable("HoSoDangKyBanHang");
                });

            modelBuilder.Entity("eShop.Entities.HoSoDangKyShipper", b =>
                {
                    b.Property<int>("HoSoDangKyShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagesChungNhanTiemVX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagesGiayXN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoSoDangKyShipperId");

                    b.ToTable("HoSoDangKyShipper");
                });

            modelBuilder.Entity("eShop.Entities.ImageSanPham", b =>
                {
                    b.Property<int>("ImageSanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameImageSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageSanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ImageSanPham");
                });

            modelBuilder.Entity("eShop.Entities.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KhachHangId");

                    b.HasIndex("CMND")
                        .IsUnique()
                        .HasFilter("[CMND] IS NOT NULL");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("eShop.Entities.LoaiSanPham", b =>
                {
                    b.Property<int>("LoaiSanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiSanPhamId");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("eShop.Entities.LuongShipper", b =>
                {
                    b.Property<int>("LuongShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipperId")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<float>("TongLuong")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LuongShipperId");

                    b.HasIndex("ShipperId");

                    b.ToTable("LuongShipper");
                });

            modelBuilder.Entity("eShop.Entities.NguoiBan", b =>
                {
                    b.Property<int>("NguoiBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HoSoDangKyBanHangId")
                        .HasColumnType("int");

                    b.Property<string>("TenCuaHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiBanId");

                    b.HasIndex("CMND")
                        .IsUnique()
                        .HasFilter("[CMND] IS NOT NULL");

                    b.HasIndex("HoSoDangKyBanHangId")
                        .IsUnique();

                    b.ToTable("NguoiBan");
                });

            modelBuilder.Entity("eShop.Entities.NguoiDung", b =>
                {
                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapDoVung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapCMND")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCapCMND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CMND");

                    b.ToTable("User");
                });

            modelBuilder.Entity("eShop.Entities.NhanVien", b =>
                {
                    b.Property<int>("IDNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNhanVien");

                    b.HasIndex("CMND")
                        .IsUnique()
                        .HasFilter("[CMND] IS NOT NULL");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("eShop.Entities.PhiHoaHongNguoiBan", b =>
                {
                    b.Property<int>("PhiHoaHongNguoiBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiBanId")
                        .HasColumnType("int");

                    b.Property<float>("PhiHoaHong")
                        .HasColumnType("real");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhiHoaHongNguoiBanId");

                    b.HasIndex("NguoiBanId");

                    b.ToTable("PhiHoaHongNguoiBan");
                });

            modelBuilder.Entity("eShop.Entities.SanPham", b =>
                {
                    b.Property<int>("SanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DiemTB")
                        .HasColumnType("real");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaSP")
                        .HasColumnType("real");

                    b.Property<int>("LoaiSanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiBanId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SanPhamId");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("NguoiBanId");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("eShop.Entities.Shipper", b =>
                {
                    b.Property<int>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HoSoDangKyShipperId")
                        .HasColumnType("int");

                    b.HasKey("ShipperId");

                    b.HasIndex("CMND")
                        .IsUnique()
                        .HasFilter("[CMND] IS NOT NULL");

                    b.HasIndex("HoSoDangKyShipperId")
                        .IsUnique();

                    b.ToTable("Shipper");
                });

            modelBuilder.Entity("eShop.Entities.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("STK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("CMND");

                    b.HasIndex("DonHangId")
                        .IsUnique();

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("eShop.Entities.TrangThaiDonHang", b =>
                {
                    b.Property<int>("TrangThaiDonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonHangId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonHangId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrangThaiDonHangId");

                    b.HasIndex("DonHangId1");

                    b.ToTable("TrangThaiDonHang");
                });

            modelBuilder.Entity("eShop.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("eShop.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.ChiTietGioHang", b =>
                {
                    b.HasOne("eShop.Entities.KhachHang", "KhachHang")
                        .WithOne("ChiTietGioHang")
                        .HasForeignKey("eShop.Entities.ChiTietGioHang", "KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietGioHang")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.DanhGiaDonHang", b =>
                {
                    b.HasOne("eShop.Entities.DonHang", "DonHang")
                        .WithOne("DanhGiaDonHang")
                        .HasForeignKey("eShop.Entities.DanhGiaDonHang", "DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.DanhGiaSanPham", b =>
                {
                    b.HasOne("eShop.Entities.ChiTietDonHang", "ChiTietDonHang")
                        .WithOne("DanhGiaSanPham")
                        .HasForeignKey("eShop.Entities.DanhGiaSanPham", "ChiTietDonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.DoanhThuNguoiBan", b =>
                {
                    b.HasOne("eShop.Entities.NguoiBan", "NguoiBan")
                        .WithMany("DoanhThuNguoiBans")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.DonHang", b =>
                {
                    b.HasOne("eShop.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.NguoiBan", "NguoiBan")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.ImageSanPham", b =>
                {
                    b.HasOne("eShop.Entities.SanPham", "SanPham")
                        .WithMany("ImageSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.KhachHang", b =>
                {
                    b.HasOne("eShop.Entities.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("eShop.Entities.KhachHang", "CMND");
                });

            modelBuilder.Entity("eShop.Entities.LuongShipper", b =>
                {
                    b.HasOne("eShop.Entities.Shipper", "Shipper")
                        .WithMany("LuongShippers")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.NguoiBan", b =>
                {
                    b.HasOne("eShop.Entities.NguoiDung", "NguoiDung")
                        .WithOne("NguoiBan")
                        .HasForeignKey("eShop.Entities.NguoiBan", "CMND");

                    b.HasOne("eShop.Entities.HoSoDangKyBanHang", "HoSoDangKyBanHang")
                        .WithOne("NguoiBan")
                        .HasForeignKey("eShop.Entities.NguoiBan", "HoSoDangKyBanHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.NhanVien", b =>
                {
                    b.HasOne("eShop.Entities.NguoiDung", "NguoiDung")
                        .WithOne("NhanVien")
                        .HasForeignKey("eShop.Entities.NhanVien", "CMND");
                });

            modelBuilder.Entity("eShop.Entities.PhiHoaHongNguoiBan", b =>
                {
                    b.HasOne("eShop.Entities.NguoiBan", "NguoiBan")
                        .WithMany("PhiHoaHongNguoiBans")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.SanPham", b =>
                {
                    b.HasOne("eShop.Entities.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShop.Entities.NguoiBan", "NguoiBan")
                        .WithMany("SanPhams")
                        .HasForeignKey("NguoiBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.Shipper", b =>
                {
                    b.HasOne("eShop.Entities.NguoiDung", "NguoiDung")
                        .WithOne("Shipper")
                        .HasForeignKey("eShop.Entities.Shipper", "CMND");

                    b.HasOne("eShop.Entities.HoSoDangKyShipper", "HoSoDangKyShipper")
                        .WithOne("Shipper")
                        .HasForeignKey("eShop.Entities.Shipper", "HoSoDangKyShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.ThanhToan", b =>
                {
                    b.HasOne("eShop.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ThanhToan")
                        .HasForeignKey("CMND");

                    b.HasOne("eShop.Entities.DonHang", "DonHang")
                        .WithOne("ThanhToan")
                        .HasForeignKey("eShop.Entities.ThanhToan", "DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eShop.Entities.TrangThaiDonHang", b =>
                {
                    b.HasOne("eShop.Entities.DonHang", "DonHang")
                        .WithMany("TrangThaiDonHangs")
                        .HasForeignKey("DonHangId1");
                });
#pragma warning restore 612, 618
        }
    }
}
